### ISSUE TITLE
Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by CWSpear** [agirorn/jasmine-slow-reporter#4]
About halfway through the tests, I got this error 3 times and then the tests ended:

```
An error was thrown in afterAll
TypeError: Cannot read property 'filename' of undefined
    at <Jasmine>
    at Object.specDone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-slow-reporter/lib/jasmine-slow-reporter.js:29:1)
    at <Jasmine>
    at ZoneQueueRunner.webpackJsonp../node_modules/zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/jasmine-patch.js:157:1)
    at <Jasmine>
```

This is using latest Jasmine (3.1).

**Comment by agirorn** [comment]
I have never used [zone.js](https://www.npmjs.com/package/zone.js?activeTab=readme) so it would be awesome if you could give me a more concrete test that fails using both libraries.

From what I can see looking at [zone.js/dist/jasmine-patch.js:157](https://github.com/angular/zone.js/blob/master/dist/jasmine-patch.js#L157) both libs a change "it/beforeEach/afterEach" functions at runtime and that must be the reason slow reporter is not getting the filename.

**Comment by agirorn** [comment]
Closing do to inactivity.
